### PR TITLE
Add ftarget

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by zaikunzhang** [comment]
Hi @jschueller Thank you so much for your very impressively prompt action!

**Comment by zaikunzhang** [comment]
Hi @jschueller ,

What is the meaning of the `value` attribute? When to use it and when not? I did not know it before. See the following for example. 

```
real(C_DOUBLE), intent(in) :: xl(n)                                                                                                  
real(C_DOUBLE), intent(in), value :: ftarget                                                                                          
```

Thanks. 

Zaikun

**Comment by zaikunzhang** [comment]
> the argument is passed by value instead of by reference (pointer)

It seems that we can only apply it to  “scalars”, not arrays?

**Comment by jschueller** [comment]
yes

**Comment by zaikunzhang** [comment]
Great. Everything looks fine. I made a few small changes regarding the workflow files. Would you mind synchronizing them before we merge the PR? Thank you very much.

**Comment by jschueller** [comment]
done

**Comment by zaikunzhang** [comment]
/////

**Pull request merged**
