### PR TITLE
Enable shared libs on win32

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by zaikunzhang** [comment]
“[temporarily remove other tests](https://github.com/libprima/prima/pull/59/commits/1dde30eb7be949dd9535a7cd4a76f4ad172e961f)”

Please remember to get them back before we merge the PR :) Thank you.

**Comment by amontoison** [comment]
I tested this PR with the cross-compiler and shared libraries and the import libraries (dll.a) are now generated on Windows.
```
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /workspace/destdir/lib/libprimaf.dll.a
-- Installing: /workspace/destdir/bin/libprimaf.dll
-- Installing: /workspace/destdir/lib/libprimac.dll.a
-- Installing: /workspace/destdir/bin/libprimac.dll
-- Installing: /workspace/destdir/lib/cmake/prima/prima-targets.cmake
-- Installing: /workspace/destdir/lib/cmake/prima/prima-targets-release.cmake
-- Installing: /workspace/destdir/lib/cmake/prima/prima-config.cmake
-- Installing: /workspace/destdir/lib/cmake/prima/prima-config-version.cmake
-- Up-to-date: /workspace/destdir/lib/libprimaf.dll.a
-- Up-to-date: /workspace/destdir/bin/libprimaf.dll
-- Installing: /workspace/destdir/include/prima/mod
-- Installing: /workspace/destdir/include/prima/mod/pintrf_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/initialize_cobyla_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/initialize_bobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/powalg_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/trustregion_newuoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/string_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/linalg_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/trustregion_bobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/geometry_newuoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/selectx_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/consts_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/getact_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/cobyla_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/update_newuoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/geometry_uobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/shiftbase_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/lincoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/geometry_bobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/xinbd_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/trustregion_lincoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/ratio_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/redrho_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/checkexit_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/infnan_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/infos_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/geometry_lincoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/uobyqb_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/trustregion_uobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/initialize_uobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/update_lincoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/uobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/fprint_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/update_bobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/cobylb_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/lincob_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/message_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/initialize_newuoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/rescue_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/history_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/debug_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/bobyqb_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/update_cobyla_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/evaluate_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/bobyqa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/initialize_lincoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/preproc_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/memory_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/trustregion_cobyla_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/newuoa_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/univar_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/geometry_cobyla_mod.mod
-- Installing: /workspace/destdir/include/prima/mod/update_uobyqa_mod.mod
-- Up-to-date: /workspace/destdir/lib/libprimac.dll.a
-- Up-to-date: /workspace/destdir/bin/libprimac.dll
-- Installing: /workspace/destdir/include/prima/prima.h
```

**Comment by zaikunzhang** [comment]
Hi, @jschueller and @amontoison ,


Thank @jschueller for the efforts!

Is this PR ready? If yes, I will merge it after @jschueller gets the deleted tests back. 

Thank you.

Best regards,
Zaikun

**Comment by jschueller** [comment]
this is good to go

**Review by amontoison — APPROVED** [review]
:+1:

**Pull request merged**
