### PR TITLE
Fix typo in LICENSE.txt

### PR DESCRIPTION
**Pull request by vchuravy**
Noticed while taking a look through the repository.

### CODE REVIEW

**Comment by zaikunzhang** [comment]
Hi @vchuravy ! Thank you very much for raising this. 

Indeed, Tom @ragonneau and I chose to write "LICENCE" instead of the more popular "LICENSE" when developing [PDFO](https://www.pdfo.net), the predecessor of PRIMA. 

The reason is that "licence" is the British version of the noun; "license" is only a verb for British. Professor Powell was British, so we guessed that he would have used "LICENCE.txt" instead of "LICENSE.txt" if he did it. Indeed, in his emails sent during his finals about the licensing issues, he used "licence" as the noun. That is why we made this particular choice. 

I must admit that I am not a native speaker, and neither is Tom. So we might have been mistaken. In that case we would be very happy to hear the correction. 

Many thanks,
Zaikun

**Review by zaikunzhang — COMMENTED** [review]
Hi @vchuravy ! Thank you very much for raising this.

Indeed, Tom @ragonneau and I chose to write "LICENCE" instead of the more popular "LICENSE" on purpose when developing [PDFO](https://www.pdfo.net/), the predecessor of PRIMA.

The reason is that "licence" is the British version of the noun; "license" is only a verb for British. Professor Powell was British, so we guessed that he would have used "LICENCE.txt" instead of "LICENSE.txt" if he did it. Indeed, in the emails sent during his final days about the licensing issues, he used "licence" as the noun. That is why we made this particular choice.

I must admit that I am not a native speaker, and neither is Tom. So we might have been mistaken. In that case, we would be very happy to hear the correction.

Many thanks,
Zaikun

**Comment by zaikunzhang** [comment]
Hi @vchuravy ,

If you find my explanation reasonable, I will close this PR this weekend. Feel free to reopen it if you would like. 

Thanks again. 

Best regards,
Zaikun

**Comment by vchuravy** [comment]
The explanation is more than reasonable :) I guess I am simply to used to the AE spelling. 

I just checked and GitHub correctly detects the license of this repository as BSD-3.

Sorry about the noise.

PS: Happy to chat about a potential Julia version :)

**Pull request closed without merging**
