### PR TITLE
CI: Disable windows/gcc11 job

### PR DESCRIPTION
**Pull request by jschueller**
this one is failing atm

### CODE REVIEW

**Comment by zaikunzhang** [comment]
Hi @jschueller , what do you think is the reason for the failure? GCC-11 is not that old. Thanks.

**Comment by nbelakovski** [comment]
I'd just like to note that I did some digging and I found this has always been failing. In CI it looks like it was passing at one point, but when I looked more closely I saw that even though the CI was downloading gcc 11, it was using gcc 12 in the build. It's not clear to me when or why it changed to use gcc 11, but when I went back to those commits and tried to test them manually with gcc11 on windows they all failed, even going as far back as the first commit to introduce the tests.

**Comment by nbelakovski** [comment]
I was able to get this to work locally by adding `/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/` to the PATH (I was using git bash, hence the `/c/...`). Essentially that directory contains `libgfortran-5.dll` which the program was unable to find otherwise. I'll take a look to see how we might fix this in CI.

**Comment by zaikunzhang** [comment]
Solved by another PR.

**Pull request closed without merging**
