### PR TITLE
Callback

### PR DESCRIPTION
**Pull request by jschueller**
Called after each iteration (Cobyla only for now).
Reports the current best x & f values.
Allows to request termination via a boolean argument.

comments welcome

### CODE REVIEW

**Comment by zaikunzhang** [comment]
Thank you Julien @jschueller . This is very nice. 

The first question that we have to discuss is as follows. In `callback(x, f, terminate, [, other inputs])`, what do we want `x` and `f` to be? There are two possibilities.
- `x` is **the current best point** and `f` is its function value
- `x` is **the most recently evaluated point** and `f` is its function value
Another possibility is to change the signature of the callback function to `callback(xnew, fnew, xbest, fbest, terminate, ...)` to include both of them.

In addition, 
- for `lincona`, we must include `cstrv` (constraint violatio) as an input to `callback`, 
- for `cobyla`, we must include both `cstrv` and `constr`.  

Insights from SciPy maintainers are greatly needed. 

Thanks.

**Comment by jschueller** [comment]
we want the best point; we already know the last point via the objective function

**Comment by jschueller** [comment]
@zaikunzhang I stumbled on a weird compiler bug:
https://github.com/flang-compiler/flang/issues/1419

**Comment by zaikunzhang** [comment]
> @zaikunzhang I stumbled on a weird compiler bug: [flang-compiler/flang#1419](https://github.com/flang-compiler/flang/issues/1419) You can add it to your collection :]

Done: https://github.com/zequipe/test_compiler/commit/1990a70f52712dc74db97a14ead54dc50c448fc2. Thank you.

**Comment by jschueller** [comment]
@zaikunzhang I added constraint values, what do you think ?

**Comment by zaikunzhang** [comment]
Hello @jschueller  Julien,

Sorry for the delayed reply. The work and life on my side have been complicated recently, and they will continue to be so for a while. 

Note the following. 

1. `[x, f, cstrv, nlconstr]` is not the latest best [decision variable, function value,  constriant violation, nonlinear constraint value]. It is the latest valued one. The latest best one is `[xbase + xpt(:, kopt), fval(kopt), cval(kopt), conmat(:, kopt)]`. 

2. `cstrv` and `nlconstr`  should be optional in `callback`. It is rather strange and confusing to define `cstrv` and `nlconstr` in subroutines like `newuob.f90`. 

Thanks.

**Pull request closed without merging**
